### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by 4gn3s** [pipermerriam/populus#159]
* Populus Version: 1.0.0b8
* OS: linux

### What was wrong?
When running `populus init` or `populus compile` in a new project directory, I get the following error:

```
Traceback (most recent call last):
  File "/home/agnieszka/.virtualenvs/shit/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/click/core.py", line 1057, in invoke
    Command.invoke(self, ctx)
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/populus/cli/main.py", line 37, in main
    if not any(is_same_path(p, project.project_dir) for p in sys.path):
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/populus/cli/main.py", line 37, in <genexpr>
    if not any(is_same_path(p, project.project_dir) for p in sys.path):
  File "/home/agnieszka/.virtualenvs/shit/local/lib/python2.7/site-packages/populus/utils/filesystem.py", line 132, in is_same_path
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

I run this command in a directory where I have two sub-directories: contracts and tests, in contracts there is 1 .sol file, and in tests there is 1 test.py file.

Is it a problem with using virtualenv python with populus?

Edit: I managed to temporarily fix the problem by commenting out [this line ](https://github.com/pipermerriam/populus/blob/master/populus/cli/main.py#L37).

#### Cute Animal Picture
![nemo](http://www.duskyswondersite.com/wp-content/uploads/2010/03/clownfish-in-anemone-2.jpg)

**Comment by pipermerriam** [comment]
#162 will fix this. thank you for reporting it.
