### ISSUE TITLE
No ImportError: No module named 'web3.utils.string'

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#247]
* Populus Version: 1.5.1
* Python 3.5
* OS: osx
* Fresh install in virtual env

### What was wrong?

```
 populus
Traceback (most recent call last):
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/bin/populus", line 7, in <module>
    from populus.cli import main
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/__init__.py", line 13, in <module>
    from .project import Project  # NOQA
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/project.py", line 26, in <module>
    from populus.migrations.migration import (
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/migrations/__init__.py", line 1, in <module>
    from .migration import (  # noqa
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/migrations/migration.py", line 8, in <module>
    from .deferred import (
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/migrations/deferred.py", line 10, in <module>
    from populus.utils.types import (
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/utils/types.py", line 10, in <module>
    from web3.utils.string import (
ImportError: No module named 'web3.utils.string'
```

`setup.py` missing pinnings?

```
                          *
                       **   **
                  * **  * * *  **
                 *   /  /   \ *  *
              \  \ /  \        / /                         (__)
           *  /  / \  \  (__)  \ \                /--------(00)
             /           (00)  / /               / |      |(  )
             \    /-------\/   \ \              *  ||---- ||()
             /   / |     ||    / /                 ||     ||
           \ \  *  ||----||    \ \                 ^^     ^^
          /  /     ^^    ^^    / /            Cow Chewing Marbles
                  Cow in Heat
 
```

**Comment by pipermerriam** [comment]
Fixed in #248
