### ISSUE TITLE
Cannot compile, solc 0.4.9

### ISSUE THREAD

**Issue by miohtama** [pipermerriam/populus#249]
* Populus Version: 1.5.1
* OS: osx

### What was wrong?

Cannot compile.

```
 populus compile
============ Compiling ==============
> Loading source files from: ./contracts

Traceback (most recent call last):
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/cli/compile_cmd.py", line 35, in compile_contracts
    compile_project_contracts(project, compiler_settings)
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/utils/cli.py", line 480, in compile_project_contracts
    compiler_settings=compiler_settings,
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/compilation.py", line 69, in compile_and_write_contracts
    compiler_settings=compiler_settings,
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/compilation.py", line 59, in compile_project_contracts
    in compiled_contracts.items()
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/compilation.py", line 58, in <genexpr>
    for contract_name, contract_data
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/utils/compile.py", line 13, in process_compiler_output
    contract_data = normalize_contract_data(data_from_compiler)
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/utils/compile.py", line 20, in normalize_contract_data
    yield 'metadata', normalize_contract_metadata(contract_data['metadata'])
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/mikko/code/wattcoin/Smart-Contracts/venv/lib/python3.5/site-packages/populus/utils/compile.py", line 36, in normalize_contract_metadata
    metadata = json.loads(metadata)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

solc --version
solc, the solidity compiler commandline interface
Version: 0.4.9+commit.364da425.Darwin.appleclang
```
#### Cute Animal Picture

```
                        O O                 O O
                         \ \               / /
                          \ \          (__) /
           (__)            \ \         (xx)/
           (DD)             \ +--------+\//
    /-------\/               \|        | /
   / |     ||                 +--------+
  *  ||----||
     ^^    ^^
 Cow fantasizing about "Riding the Mechanical Bull"
```

**Comment by pipermerriam** [comment]
It's not actually clear whether this is the same issue as https://github.com/ethereum/solidity/issues/1645 but populus and solidity `0.4.9` don't get along well right now.
