### ISSUE TITLE
KeyError: 'priority' when "$ populus deploy --chain horton Greeter"

### ISSUE THREAD

**Issue by kichinosukey** [pipermerriam/populus#299]
* Populus Version: 1.6.9
* OS: osx

### What was wrong?
I'm doing Part 2:Local Chain of this site http://populus.readthedocs.io/en/latest/tutorial.part-2.html
But error has occured. I'm not sure how fix it.

* full output
> Found 1 contract source files
  - contracts/Greeter.sol
> Compiled 1 contracts
  - Greeter
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/config/base.py", line 135, in __getitem__
    return self.resolve(get_nested_key(self._wrapped, key))
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/utils/mappings.py", line 46, in get_nested_key
    return getter_fn(config)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/eth_utils/functional.py", line 11, in <lambda>
    return lambda x: f(g(x))
KeyError: 'priority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.5.1/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/cli/deploy_cmd.py", line 90, in deploy_cmd
    provider = chain.provider
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/chain/base.py", line 140, in provider
    if not self.provider_backends:
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/chain/base.py", line 134, in provider_backends
    for backend_name, backend in self.contract_backends.items():
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/utils/functional.py", line 27, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/chain/base.py", line 121, in contract_backends
    for backend_name, backend_config in self.contract_backend_configs.items():
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/chain/base.py", line 113, in contract_backend_configs
    self.project.config
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/utils/config.py", line 107, in sort_prioritized_configs
    in resolved_backend_configs
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/collections/__init__.py", line 514, in __init__
    self.update(*args, **kwds)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/collections/__init__.py", line 601, in update
    _count_elements(self, iterable)
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/utils/config.py", line 106, in <genexpr>
    for backend_name, config
  File "/Users/xxx/.pyenv/versions/3.5.1/lib/python3.5/site-packages/populus/config/base.py", line 137, in __getitem__
    raise KeyError("Key '{0}' not found in {1}".format(key, self._wrapped))
KeyError: "Key 'priority' not found in {}"

* what command you ran
$ populus deploy --chain horton Greeter

#### Cute Animal Picture
<img width="120" alt="2017-06-17 19 11 09" src="https://user-images.githubusercontent.com/16971524/27252112-cb052768-5390-11e7-93d6-d65fca45a25c.png">

**Comment by pipermerriam** [comment]
Guessing this is due to outdated tutorial code.  Will try to dig into this soon.
