### ISSUE TITLE
Incorrect argument count

### ISSUE THREAD

**Issue by gelinger777** [pipermerriam/populus#317]
* Populus Version: 1.6.8
* OS: linux

### What was wrong?

Strange Error 

```
(venv) mymaps@mymaps-ThinkPad-E550:~/Desktop/taza/ico$ deploy-token --chain=mainnet --address=0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9 --contract-name=CrowdsaleToken --name=Xtoken --symbol=XXY --supply=2000000 --decimals=8 --verify --verify-filename=CrowdsaleToken.sol 
Web3 provider is RPC connection http://127.0.0.1:8545
Deployer address is 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9
Deployer balance is 1.385531752 ETH
Starting contract deployment
['Xtoken', 'XXY', 200000000000000, 8]
Traceback (most recent call last):
  File "/usr/local/bin/deploy-token", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/taza/ico/ico/cmd/deploytoken.py", line 74, in main
    contract, txhash = c.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_args=args)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 154, in deploy_contract
    kwargs=deploy_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 295, in deploy
    deploy_transaction['data'] = cls._encode_constructor_data(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 732, in _encode_constructor_data
    arguments = merge_args_and_kwargs(constructor_abi, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 71, in inner
    return fn(*text_args, **text_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/abi.py", line 152, in merge_args_and_kwargs
    len(args) + len(kwargs),
TypeError: Incorrect argument count.  Expected '5'.  Got '4'
```

I am trying to use the tokenmarket's ICO tool which is based on Populus 1.6.8 

In the dployment script it's using 

    contract, txhash = c.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_args=args)

which apparently leads to the error above.  Any ideas how to fix it? 

#### Cute Animal Picture
![Image of Yaktocat](http://cdn.akc.org/Marketplace/Breeds/Bullmastiff_SERP.jpg)

**Comment by pipermerriam** [comment]
You are not passing enough arguments to the constructor of your contract.

```
File "/home/mymaps/Desktop/taza/ico/ico/cmd/deploytoken.py", line 74, in main
```

Looks like you're one argument short.

**Comment by gelinger777** [comment]
This I understand, but I don't understand which param is missing...

**Comment by gelinger777** [comment]
here is the command line 


      `contract, txhash = c.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_args=args)`

**Comment by gelinger777** [comment]
code till that part is quite sample 

```
"""Deploy tokens contract."""
import os
import time
import sys
import datetime

import click
from eth_utils import from_wei
from eth_utils import to_wei
from populus.utils.accounts import is_account_locked
from populus import Project
from populus.utils.cli import request_account_unlock

from ico.utils import check_succesful_tx
from ico.utils import get_constructor_arguments
from ico.etherscan import verify_contract
from ico.etherscan import get_etherscan_link


@click.command()
@click.option('--chain', nargs=1, default="mainnet", help='On which chain to deploy - see populus.json')
@click.option('--address', nargs=1, help='Address to deploy from and who becomes as a owner (must exist on geth)', required=True)
@click.option('--contract-name', nargs=1, help='Name of the token contract', default="CentrallyIssuedToken")
@click.option('--release-agent', nargs=1, help='Address that acts as a release agent (can be same as owner)', default=None)
@click.option('--minting-agent', nargs=1, help='Address that acts as a minting agent (can be same as owner)', default=None)
@click.option('--name', nargs=1, required=True, help='Token name', type=str)
@click.option('--symbol', nargs=1, required=True, help='Token symbol', type=str)
@click.option('--supply', nargs=1, default=21000000, help='Initial token supply (multipled with decimals)', type=int)
@click.option('--decimals', nargs=1, default=0, help='How many decimal points the token has', type=int)
@click.option('--verify/--no-verify', default=False, help='Verify contract on EtherScan.io')
@click.option('--verify-filename', nargs=1, help='Solidity source file of the token contract for verification', default=None)
@click.option('--master-address', nargs=1, help='Move tokens and upgrade master to this account', default=None)
def main(chain, address, contract_name, name, symbol, supply, decimals, minting_agent, release_agent, verify, verify_filename, master_address):
    """Deploy a token contract.

    Examples:

    deploy-token --chain=ropsten --address=0x3c2d4e5eae8c4a31ccc56075b5fd81307b1627c6 --name="MikkoToken 2.0" --symbol=MOO --release-agent=0x3c2d4e5eae8c4a31ccc56075b5fd81307b1627c6  --supply=100000

    deploy-token --chain=kovan --contract-name="CentrallyIssuedToken" --address=0x001FC7d7E506866aEAB82C11dA515E9DD6D02c25  --name="TestToken" --symbol=MOO --supply=916 --decimals=0 --verify --verify-filename=CentrallyIssuedToken.sol
    """

    project = Project()

    with project.get_chain(chain) as c:

        web3 = c.web3
        print("Web3 provider is", web3.currentProvider)
        print("Deployer address is", address)
        print("Deployer balance is", from_wei(web3.eth.getBalance(address), "ether"), "ETH")

        # Goes through geth account unlock process if needed
        if is_account_locked(web3, address):
            request_account_unlock(c, address, None)

        decimal_multiplier = 10 ** decimals

        transaction = {"from": address}
        args = [name, symbol, supply * decimal_multiplier, decimals]

        #if contract_name == "CentrallyIssuedToken":
            # TODO: Generalize settings contract args
            # This sets the upgrade master
        args = [address] + args

        # Make sure Populus does not pull up any cached instances of deployed contracts
        # TODO: Fix Populus support this via an deploy argument
        if "JSONFile" in c.registrar.registrar_backends:
            del c.registrar.registrar_backends["JSONFile"]

        print("Starting contract deployment")
        # This does deployment with all dependencies linked in
        contract, txhash = c.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_args=args)
        check_succesful_tx(web3, txhash)
        print("Contract address is", contract.address)
```

**Comment by gelinger777** [comment]
and when the arguments passed are  enough I am getting following 

```
Deployer balance is 1.339281012 ETH
Starting contract deployment
Traceback (most recent call last):
  File "/usr/local/bin/deploy-token", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/taza/ico/ico/cmd/deploytoken.py", line 73, in main
    contract, txhash = c.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_args=args)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 154, in deploy_contract
    kwargs=deploy_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 295, in deploy
    deploy_transaction['data'] = cls._encode_constructor_data(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 735, in _encode_constructor_data
    cls._encode_abi(constructor_abi, arguments, data=cls.bytecode)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 690, in _encode_abi
    ', '.join(argument_types),
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: string, string, uint256, uint256, bool
```

**Comment by pipermerriam** [comment]
Can you post the function signature for the constructor of your contract and the arguments you are passing in as `args` to the `deploy` method?

**Comment by gelinger777** [comment]
its a bit complicated. I user TokenMarketNet ICO tool 
https://github.com/TokenMarketNet/ico

One question, could you clearify me how populus counts arguments needed?

**Comment by gelinger777** [comment]
how populus determines that the contract needs 5 arguments to be deployed?

**Comment by gelinger777** [comment]
@pipermerriam  Could you help to clear this? How populus counts the arguments? Does it take it from like populus json or  what?

**Comment by pipermerriam** [comment]
@gelinger777 I think we got this figured out today.  Let me know if this should be re-opened.

**Comment by mandarvaze** [comment]
@pipermerriam @gelinger777 : What was the "solution" ?
