### ISSUE TITLE
Must have at least one provider backend configured

### ISSUE THREAD

**Issue by drandreaskrueger** [pipermerriam/populus#367]
* Populus Version: x.x.x

```
populus version
Error: No such command "version".

populus --version
Error: no such option: --version
```
(installed today, via pip)

* OS: osx/linux/win

```
uname -a 
Linux ... 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

### What am I doing wrong?
When I do 

```
populus init 
populus compile
py.test 
```
it's all good, but then with
```
populus deploy Greeter --chain CRS --no-wait-for-sync
```

I get a 

```
> Found 1 contract source files
  - contracts/Greeter.sol
> Compiled 1 contracts
  - contracts/Greeter.sol:Greeter
Traceback (most recent call last):
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/populus/cli/deploy_cmd.py", line 43, in deploy_cmd
    deploy(project, logger, chain_name, wait_for_sync, contracts_to_deploy)
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/populus/api/deploy.py", line 78, in deploy
    provider = chain.provider
  File "/home/akrueger/Documents/Code/LiClipseWorkspace/EPE/env/epe-py3/lib/python3.5/site-packages/populus/chain/base.py", line 137, in provider
    "configured\n{0}".format(self.contract_backend_configs)
ValueError: Must have at least one provider backend configured
OrderedDict()
```

This is my package.json
```
{
  "version":"7",
  "compilation":{
    "contracts_source_dirs": ["./contracts"],
    "import_remappings": []
  },

    "chains": {
      "CRS": {
            "eth": {
            "default_account": "0x0000000000000000000000000000000000000001"
          },
        "chain": {
          "class": "populus.chain.ExternalChain"
        },
        "web3": {
          "provider": {
            "class": "web3.providers.rpc.HTTPProvider",
            "settings": {
              "endpoint_uri": "https://127.0.0.1:8545"
            }
          }
        }
      }
    }
}
```

I have my own parity instance running, on port 8545, on a private chain.

What haven't I understood?

Thanks a lot!

#### Cute Animal Picture

> put a cute animal picture here.

![cartoon-monkey-funny-monkeys.jpg](https://i.pinimg.com/236x/ca/c9/9a/cac99ade217eabdc7b5a1b5c93694317--cartoon-monkey-funny-monkeys.jpg)

**Comment by dubh3124** [comment]
Hi,

 I ran into the same problem. You are missing the "contracts" key/value. This worked for me:

```
{
  "version":"7",
  "compilation":{
    "contracts_source_dirs": ["./contracts"],
    "import_remappings": [],
    "backend":{
      "class":"populus.compilation.backends.SolcStandardJSONBackend",
      "settings":{
         "stdin":{
            "optimizer":{
               "enabled":true,
               "runs":500
            },
            "outputSelection":{
               "*":{
                  "*":[
                     "abi",
                     "metadata",
                     "evm.bytecode",
                     "evm.deployedBytecode"
                  ]
               }
            }
         }
      }
   }
  },
  "chains": {
   "ext_chain": {
    "chain": {
      "class": "populus.chain.ExternalChain"
     },
    "web3": {
      "provider": {
        "class": "web3.providers.rpc.HTTPProvider",
        "settings": {
          "endpoint_uri": "http://127.0.0.1:8545"
        }
      }
    },
    "contracts": {
        "backends": {
          "JSONFile": {"$ref": "contracts.backends.JSONFile"},
          "ProjectContracts": {
            "$ref": "contracts.backends.ProjectContracts"
          }
        }
      }
  }
}
}
```

**Comment by paultiplady** [comment]
Ugh just burned an hour plus on this one too -- this should be in the docs somewhere. Added this: https://github.com/ethereum/populus/pull/439
