### ISSUE TITLE
populus init doesn't create a libraries folder by default

### ISSUE THREAD

**Issue by euri10** [pipermerriam/populus#80]
### What was wrong?
when running populus web runserver I got this error that the libraries folder doesn't exist.

```
➜  testpopulus populus web runserver
Compiling contracts...
Compiling contracts.js...
Collectind static assets...
Traceback (most recent call last):
  File "/usr/local/bin/populus", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/populus/cli/web_cmd.py", line 95, in web_runserver
    contracts_observer_thread.start()
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/usr/local/lib/python2.7/dist-packages/watchdog/utils/__init__.py", line 111, in start
    self.on_thread_start()
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/polling.py", line 77, in on_thread_start
    self._snapshot = self._take_snapshot()
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/polling.py", line 74, in <lambda>
    self.watch.path, self.watch.is_recursive, stat=stat, listdir=listdir)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/utils/dirsnapshot.py", line 207, in __init__
    st = stat(path)
OSError: [Errno 2] No such file or directory: '/home/lotso/PycharmProjects/testpopulus/libraries'
```

### How was it fixed?

I got no issue to do a little mkdir libraries but it would be simpler imho to create it with the init command.

#### Cute Animal Picture

![Cute Animal Picture](https://upload.wikimedia.org/wikipedia/commons/d/d9/Florida_Box_Turtle_Digon3a.jpg)

**Comment by pipermerriam** [comment]
Thanks for reporting this.  You can find a release with this fixed in on pypi under `0.7.5`
